manifest:
  # defaults:
  #   revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: petejohanson
      import: app/west.yml
      revision: core/move-to-zephyr-4-1
  self:
    path: config
